name: RIF faucet deploy to prod
on:
  push:
    branches:
      - 'master'

jobs:
  main_build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Node version
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Build site
      run: yarn build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MAIN_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.MAIN_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.MAIN_AWS_REGION }}

    - name: Deploy site to S3
      run: |
        aws s3 sync --delete --only-show-errors build/ ${{ secrets.MAIN_S3_BUCKET }}

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.MAIN_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
